/**
 * SVG Export for perspektive.js
 *
 * Generates a spec-compliant SVG document from graph data, rendering:
 * - The Poincare disk boundary as a crisp circle
 * - Hyperbolic geodesic edges as SVG arc commands (matching the WebGL geodesics)
 * - Colored node circles following the cyberpunk palette
 * - Labels for high-energy nodes
 *
 * The output is a standalone SVG file that opens correctly in Inkscape,
 * Adobe Illustrator, browsers, and any SVG-compliant viewer.
 */

import type { ExportOptions, GraphExportData } from './types';
import { NODE_TYPE_COLORS, UBERMENSCH_COLOR } from './types';
import { downloadFile, defaultFilename, escapeXml } from './utils';

/** Default SVG canvas dimensions (logical pixels). */
const DEFAULT_SIZE = 1024;

/** Poincare disk radius in SVG coordinate space. */
const DISK_RADIUS_RATIO = 0.45;

/** Epsilon for detecting near-zero denominators in geodesic calculation. */
const EPSILON = 1e-6;

/** Minimum distance between two points to draw an edge. */
const MIN_EDGE_LENGTH = 1e-4;

/**
 * Generate an SVG string from graph data and download it as a .svg file.
 *
 * @param data - The structured graph export data (nodes, edges, metadata).
 * @param options - Optional export configuration (filename, width, height, background).
 *
 * @example
 * ```ts
 * exportToSVG(graphData, { filename: 'my-graph', width: 2048, height: 2048 });
 * ```
 */
export function exportToSVG(data: GraphExportData, options?: ExportOptions): void {
  const svg = generateSVGString(data, options);
  const filename = options?.filename
    ? `${options.filename}.svg`
    : defaultFilename('perspektive', 'svg');

  downloadFile(svg, filename, 'image/svg+xml');
}

/**
 * Generate the SVG string without triggering a download.
 * Useful for clipboard operations or embedding in other documents.
 *
 * @param data - The structured graph export data.
 * @param options - Optional export configuration.
 * @returns A complete, valid SVG document as a string.
 */
export function generateSVGString(data: GraphExportData, options?: ExportOptions): string {
  const width = options?.width ?? DEFAULT_SIZE;
  const height = options?.height ?? DEFAULT_SIZE;
  const background = options?.background ?? '#000000';

  const cx = width / 2;
  const cy = height / 2;
  const diskRadius = Math.min(width, height) * DISK_RADIUS_RATIO;

  const nodeMap = new Map(data.nodes.map(n => [n.id, n]));

  // Build SVG parts
  const parts: string[] = [];

  // XML declaration and SVG root
  parts.push('<?xml version="1.0" encoding="UTF-8" standalone="no"?>');
  parts.push(
    `<svg xmlns="http://www.w3.org/2000/svg" ` +
    `xmlns:xlink="http://www.w3.org/1999/xlink" ` +
    `viewBox="0 0 ${width} ${height}" ` +
    `width="${width}" height="${height}" ` +
    `style="background:${background}">`
  );

  // Metadata comment
  parts.push(`  <!-- Generated by perspektive.js ${data.metadata?.perspektiveVersion ?? '0.1.0'} -->`);
  if (data.metadata?.exportedAt) {
    parts.push(`  <!-- Exported: ${escapeXml(data.metadata.exportedAt)} -->`);
  }
  if (data.metadata?.collection) {
    parts.push(`  <!-- Collection: ${escapeXml(data.metadata.collection)} -->`);
  }

  // Definitions: glow filter for neon effect
  parts.push('  <defs>');
  parts.push('    <filter id="neonGlow" x="-50%" y="-50%" width="200%" height="200%">');
  parts.push('      <feGaussianBlur in="SourceGraphic" stdDeviation="2" result="blur"/>');
  parts.push('      <feMerge>');
  parts.push('        <feMergeNode in="blur"/>');
  parts.push('        <feMergeNode in="SourceGraphic"/>');
  parts.push('      </feMerge>');
  parts.push('    </filter>');
  parts.push('    <filter id="strongGlow" x="-50%" y="-50%" width="200%" height="200%">');
  parts.push('      <feGaussianBlur in="SourceGraphic" stdDeviation="4" result="blur"/>');
  parts.push('      <feMerge>');
  parts.push('        <feMergeNode in="blur"/>');
  parts.push('        <feMergeNode in="blur"/>');
  parts.push('        <feMergeNode in="SourceGraphic"/>');
  parts.push('      </feMerge>');
  parts.push('    </filter>');
  // Clipping mask for the disk interior
  parts.push(`    <clipPath id="diskClip">`);
  parts.push(`      <circle cx="${cx}" cy="${cy}" r="${diskRadius}"/>`);
  parts.push(`    </clipPath>`);
  parts.push('  </defs>');

  // Background rectangle
  parts.push(`  <rect width="${width}" height="${height}" fill="${background}"/>`);

  // Poincare disk background (the "abyss")
  parts.push(`  <circle cx="${cx}" cy="${cy}" r="${diskRadius}" fill="#050510"/>`);

  // Disk border
  parts.push(
    `  <circle cx="${cx}" cy="${cy}" r="${diskRadius}" ` +
    `fill="none" stroke="#1e293b" stroke-width="1" opacity="0.5"/>`
  );

  // Edges group (clipped to disk interior)
  parts.push(`  <g clip-path="url(#diskClip)" opacity="0.6">`);

  for (const edge of data.edges) {
    const p1 = nodeMap.get(edge.source);
    const p2 = nodeMap.get(edge.target);
    if (!p1 || !p2) continue;

    const svgPath = buildGeodesicSVGPath(
      p1.x, p1.y, p2.x, p2.y, cx, cy, diskRadius
    );
    if (!svgPath) continue;

    const opacity = Math.min(0.1 + edge.weight * 0.4, 0.8);

    parts.push(
      `    <path d="${svgPath}" ` +
      `fill="none" stroke="#00d8ff" stroke-width="0.8" ` +
      `opacity="${opacity.toFixed(2)}" ` +
      `filter="url(#neonGlow)"/>`
    );
  }

  parts.push('  </g>');

  // Nodes group
  parts.push('  <g>');

  // Sort so high-energy nodes render on top
  const sortedNodes = [...data.nodes].sort((a, b) => a.energy - b.energy);

  for (const node of sortedNodes) {
    const svgX = cx + node.x * diskRadius;
    const svgY = cy - node.y * diskRadius; // SVG Y is inverted vs. math Y

    // Node radius: base + energy scaling, with conformal compensation
    const norm = Math.sqrt(node.x * node.x + node.y * node.y);
    const conformalFactor = 2 / Math.max(1 - norm * norm, 0.01);
    const baseRadius = 3 + node.energy * 8;
    const visualRadius = Math.max(baseRadius / conformalFactor, 1.5);

    // Color selection following the WebGL palette
    let fillColor: string;
    const isUbermensch = node.energy > 0.8;

    if (isUbermensch) {
      fillColor = UBERMENSCH_COLOR;
    } else {
      fillColor = NODE_TYPE_COLORS[node.node_type] ?? NODE_TYPE_COLORS['Semantic'];
    }

    const glowFilter = isUbermensch ? 'url(#strongGlow)' : 'url(#neonGlow)';

    parts.push(
      `    <circle cx="${svgX.toFixed(2)}" cy="${svgY.toFixed(2)}" ` +
      `r="${visualRadius.toFixed(2)}" fill="${fillColor}" ` +
      `filter="${glowFilter}" ` +
      `opacity="${isUbermensch ? '1' : '0.9'}"/>`
    );

    // Labels for high-energy nodes (energy > 0.6)
    if (node.energy > 0.6) {
      const labelId = node.id.length > 12 ? node.id.substring(0, 12) + '...' : node.id;
      const labelColor = isUbermensch ? UBERMENSCH_COLOR : '#94a3b8';
      const fontSize = isUbermensch ? 9 : 7;

      parts.push(
        `    <text x="${(svgX + visualRadius + 3).toFixed(2)}" ` +
        `y="${(svgY + 3).toFixed(2)}" ` +
        `fill="${labelColor}" font-family="monospace" font-size="${fontSize}" ` +
        `opacity="0.8">${escapeXml(labelId)}</text>`
      );
    }
  }

  parts.push('  </g>');

  // Legend
  parts.push('  <g transform="translate(20, 20)">');
  parts.push('    <text fill="#00f0ff" font-family="monospace" font-size="14" font-weight="bold">');
  parts.push('      NietzscheDB // Perspektive.js');
  parts.push('    </text>');

  let legendY = 30;
  const legendEntries: [string, string][] = [
    ['Semantic', NODE_TYPE_COLORS['Semantic']],
    ['Episodic', NODE_TYPE_COLORS['Episodic']],
    ['Concept', NODE_TYPE_COLORS['Concept']],
    ['DreamSnapshot', NODE_TYPE_COLORS['DreamSnapshot']],
    ['Ubermensch (E>0.8)', UBERMENSCH_COLOR],
    ['Pruned', NODE_TYPE_COLORS['Pruned']],
  ];

  for (const [label, color] of legendEntries) {
    parts.push(
      `    <circle cx="8" cy="${legendY}" r="4" fill="${color}"/>` +
      `    <text x="18" y="${legendY + 4}" fill="#94a3b8" font-family="monospace" font-size="10">${escapeXml(label)}</text>`
    );
    legendY += 18;
  }

  // Stats
  legendY += 8;
  parts.push(
    `    <text x="0" y="${legendY}" fill="#00f0ff" font-family="monospace" font-size="10" opacity="0.7">` +
    `NODES: ${data.nodes.length} | EDGES: ${data.edges.length}</text>`
  );

  if (data.metadata?.manifold) {
    legendY += 14;
    parts.push(
      `    <text x="0" y="${legendY}" fill="#00f0ff" font-family="monospace" font-size="10" opacity="0.7">` +
      `MANIFOLD: ${escapeXml(data.metadata.manifold.toUpperCase())}</text>`
    );
  }

  parts.push('  </g>');

  // Close SVG
  parts.push('</svg>');

  return parts.join('\n');
}

/**
 * Build an SVG path `d` attribute for a hyperbolic geodesic between two points.
 *
 * In the Poincare disk model, geodesics are either:
 * - Straight lines through the origin (diameters), or
 * - Circular arcs orthogonal to the boundary circle.
 *
 * This function computes the orthogonal circle parameters (using the same
 * Cramer's rule approach as the WebGL renderer) and converts them to SVG
 * arc commands (`A rx ry rotation large-arc-flag sweep-flag x y`).
 *
 * @param x1 - Source X in Poincare coordinates [-1, 1].
 * @param y1 - Source Y in Poincare coordinates [-1, 1].
 * @param x2 - Target X in Poincare coordinates [-1, 1].
 * @param y2 - Target Y in Poincare coordinates [-1, 1].
 * @param cx - SVG canvas center X.
 * @param cy - SVG canvas center Y.
 * @param diskRadius - Radius of the Poincare disk in SVG pixels.
 * @returns An SVG path `d` string, or null if the edge is degenerate.
 */
function buildGeodesicSVGPath(
  x1: number, y1: number,
  x2: number, y2: number,
  cx: number, cy: number,
  diskRadius: number,
): string | null {
  // Check for degenerate edge (two coincident points)
  const dx = x2 - x1;
  const dy = y2 - y1;
  if (Math.sqrt(dx * dx + dy * dy) < MIN_EDGE_LENGTH) return null;

  // SVG coordinates (note: SVG Y is inverted)
  const sx1 = cx + x1 * diskRadius;
  const sy1 = cy - y1 * diskRadius;
  const sx2 = cx + x2 * diskRadius;
  const sy2 = cy - y2 * diskRadius;

  // Check if points are collinear with origin (denominator of Cramer system ~ 0)
  const denominator = 2 * (x1 * y2 - x2 * y1);

  if (Math.abs(denominator) < EPSILON) {
    // Geodesic is a straight line (diameter of the disk)
    return `M ${sx1.toFixed(2)} ${sy1.toFixed(2)} L ${sx2.toFixed(2)} ${sy2.toFixed(2)}`;
  }

  // Compute the center and radius of the orthogonal circle using Cramer's rule
  const d1 = x1 * x1 + y1 * y1;
  const d2 = x2 * x2 + y2 * y2;

  const ocx = ((1 + d1) * y2 - (1 + d2) * y1) / denominator;
  const ocy = (x1 * (1 + d2) - x2 * (1 + d1)) / denominator;

  // Radius of the orthogonal circle: r^2 = |center|^2 - 1
  const rSq = ocx * ocx + ocy * ocy - 1;
  if (rSq <= 0) {
    // Degenerate case: fall back to straight line
    return `M ${sx1.toFixed(2)} ${sy1.toFixed(2)} L ${sx2.toFixed(2)} ${sy2.toFixed(2)}`;
  }
  const orthoRadius = Math.sqrt(rSq);

  // Convert orthogonal circle radius to SVG pixel space
  const svgRadius = orthoRadius * diskRadius;

  // Determine arc flags for the SVG `A` command.
  // We want the SHORTER arc (the one inside the disk).
  // Compute the cross product to determine sweep direction.
  // Vector from orthogonal center to p1 and p2:
  const v1x = x1 - ocx;
  const v1y = y1 - ocy;
  const v2x = x2 - ocx;
  const v2y = y2 - ocy;

  // Cross product (z-component) determines winding
  const cross = v1x * v2y - v1y * v2x;

  // Angle subtended by the arc
  const dot = v1x * v2x + v1y * v2y;
  const mag1 = Math.sqrt(v1x * v1x + v1y * v1y);
  const mag2 = Math.sqrt(v2x * v2x + v2y * v2y);
  const cosAngle = Math.max(-1, Math.min(1, dot / (mag1 * mag2)));
  const angle = Math.acos(cosAngle);

  // large-arc-flag: 1 if arc > 180 degrees
  const largeArc = angle > Math.PI ? 1 : 0;

  // sweep-flag: in SVG coordinate system (Y inverted), we need to flip
  // the sweep when cross product is negative (because Y inversion flips winding)
  const sweep = cross > 0 ? 0 : 1;

  return (
    `M ${sx1.toFixed(2)} ${sy1.toFixed(2)} ` +
    `A ${svgRadius.toFixed(2)} ${svgRadius.toFixed(2)} 0 ${largeArc} ${sweep} ` +
    `${sx2.toFixed(2)} ${sy2.toFixed(2)}`
  );
}
